spring:
  profiles:
    active: eureka2
---
spring:
  profiles: eureka1
  application:
    name: item-service

server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka
---
spring:
  profiles: eureka2
  application:
    name: item-service

server:
  port: 8002
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2002/eureka,http://eureka2:2002/eureka
